### ISSUE TITLE
Update ds-prep-course-2021 readme with the 2021 setup guide

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/ds-prep-course-2021#2]
* mostly copy from https://github.com/LDSSA/ds-prep-course
* Remove vmware mentions (we will not support it this year)
* Add installing python 3.7 and using it to create all virtual environments

**Comment by Juliana-R** [comment]
On it.

**Comment by buedaswag** [comment]
FYI i'll rename the `SLU000 - Jupyter Notebook` folder to `SLU00 - Jupyter Notebook` to keep it consistent with the rest of the LUs

**Comment by Juliana-R** [comment]
I love that! Will change accordingly.

**Comment by mariana-s-fernandes** [comment]
Just noticed you've already included a comment about Git authentication. I was reading about it and, for people with 2FA enabled, I believe they need [another process](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token), not sure if you should mention that or not.

**Comment by Juliana-R** [comment]
Thanks @mariana-s-fernandes !  I didn't even think about that.

The section on Git is mainly for people who don't yet have a GitHub account, so I'd suppose it would default to the basic authentication. However this makes me question whether on new accounts GitHub is already adopting the new method of authentication.

I'm totally clueless though. Do you have a suggestion of what I could write here? 🙏

**Comment by mariana-s-fernandes** [comment]
Let me try to go through the process on my side, so I see how can we do it!

**Comment by Juliana-R** [comment]
thank you!!
<br>
![image](https://user-images.githubusercontent.com/52176135/111802829-566fc600-88c6-11eb-8d83-7d1073df154c.png)

**Comment by mariana-s-fernandes** [comment]
@Juliana-R  Ok, this worked for me. I followed the instructions [here](https://webkul.com/blog/github-push-with-two-factor-authentication/). You can say something like:

If you already have a Github account and you have 2FA enabled, you need an extra step and simply inputting your password will not work. In this case, you can go to [https://github.com/settings/tokens](https://github.com/settings/tokens), click on `Generate new token`. You can give it a name in the note field, we suggest you use `ldsa-token`. Then select `repo` in the scopes and click on `Generate token`.  You will be prompted with a code that you should save (you will not be able to see it again after leaving that window). Now use this code instead of your password when cloning your repo.

Feel free to change it, this is just a suggestion of text 😄

**Comment by Juliana-R** [comment]
That's actually very well written @mariana-s-fernandes. Thank you, I'll add it!! 🙏 

By the way: Do you like writing and structuring stuff? Because that quality of writing would be more than welcome at the Documentation AOR. 😁
